### ISSUE TITLE
Error during fitting

### ISSUE THREAD

**Issue by Morgan435** [pyCGM2/pyCGM2#2]
@aaa34169 I run the pycgm operation on the walking trial of the subject we have been battling with (for static calibration) and run into another error. Please find the 
![screen shot 03-09-17 at 12 15 pm](https://cloud.githubusercontent.com/assets/12653708/23731499/25ed8e22-04c2-11e7-9caf-f991a8c96d69.PNG)
screenshot of the log.

**Comment by aaa34169** [comment]
hi Morgan, 

I just have a look at your c3d. Why didn t you crop your c3d ? 
pyCGM2 works fine with frames containing no gaps.

**Comment by Morgan435** [comment]
We only rarely crop our walking files, sorry. 
pyCGM2 should still be working when they are some gaps.

**Comment by aaa34169** [comment]
aie :-(, you touch a weak point.
My current code can t fullfill this request. 
I don t tell you i woudn t do that ,but there are too much modifications.

**Comment by Morgan435** [comment]
I am afraid you might still need to address the issue. Gaps are likely to exist in the users files and, since pyCGM2 is meant to be a replacement of PiG, they won't understand why PiG can process the trial and pyCGM2 cannot (because of the gaps).

The way I have solved the issue with Vilab is that I am checking the entire trial at the beginning and I construct a Boolean vector (of size Nframes) that stores if the frame can be processed (for me it is simple: at least 3 markers for each segment available). The fitting procedure loops through this vector, rather than for every frame. 
You can also post-process this vector before fitting if need be. For example, if you need to have at least one good frame on either side of each processing frame (for derivation purposes) you can set the frames that do not satisfy this criteria to false, etc.

**Comment by Alzathar** [comment]
FYI, the project [OpenMA](http://github.com/openma/openma) already manages data occlusion and sets in consequence residuals of generated results (i.e. joint kinematics and kinetics). We are also working on the issue openma/openma#11 to delete automatically segments and children when markers are completely missing. There is also a plan to implement an advanced gap filling.

OpenMA is not ready to support the CGM 1.x - 3.x models (the internal structure is not flexible enough), but we are working on this (see the [roadmap](https://github.com/OpenMA/openma/wiki/Roadmap) for more details).

**Comment by aaa34169** [comment]
Hi Morgan

I found out error is not where you pointed out. it s a warning  
Error is at detection of travelling global axis. 
my function ```findProgressionFromPoints``` uses first frame and pelvic markers to detect the traveling global axis firstly and if your trial is a back-way trial secondly.
As you didn t have any pelvic marker at first frame, code fails. 
I am going to improve the function

cheers

**Comment by Morgan435** [comment]
Another reason to make pyCGM2 gaps proof?

**Comment by aaa34169** [comment]
sentence not clear for me, sorry :-(
need explanation

**Comment by Morgan435** [comment]
Meaning: the issue is linked to the presence of gaps, rather than modifying your function I would modify the structure of the code so that it works with the same function. In this case, the pre-checking of good frames would feed your function only with the appropriate first good frame and all will be good.

**Comment by aaa34169** [comment]
I kept idea of a pre-checking function 
I have modified internal code. 
Tomorrow , I will verify my tests and propose a new commit.
