### ISSUE TITLE
different angles from Static PIG and dynamic PIG vicon Operations 

### ISSUE THREAD

**Issue by aaa34169** [pyCGM2/pyCGM2#3]
Technicaly, the static PIG operation ( native vicon C++) aims at returning offsets then considering during dynamic operation. 
However, the static operation also returns angles, which could be analyses from a quality point of view. 

**I am concerning that these angles and those from the dynamic PIG operation are different**

 * with a simple PIG : only ankle angles are different
 * with KAD and KADmed variants, all joint angles are different

**Comment by Morgan435** [comment]
I believe we should apply our policy about the CGM1.0 and 1.1 versions here as well.

CGM 1.0 is meant to reproduce PiG exactly, i.e. including the differences in static and dynamic angles at the knee.
CGM 1.1 is meant to correct what is incorrect, illogical or undocumented in PiG. These differences between static and dynamic outputs are undocumented and misleading, so I think we should correct them.

That also means we have to make a choice: do we output the knee angle as (1) femur vs tibia (lateral axis of the tibia being aligned with the bimalleolar axis) or (2) femur vs proximal tibia (lateral proximal tibia aligned with the lateral axis of the femur during static).
At the moment static PiG outputs (1) whereas dynamic PiG outputs (2). I am in favour of (1) because this is what is done for all other joints (there is no static offset) and it would make the report of kinematics more consistent.

**Comment by rjbakersalford** [comment]
OK, thanks for the explanation Morgan, I'd forgotten this (I didn't know about this despite often thinking that static PiG knee outputs didn't look correct - I feel a little embarrassed to find out that the answer is so simple!).

I think the logic you develop is correct and agree that CGM 1.0 should do what PiG does. I also agree that this is wrong and therefore should be corrected in CGM 1.1 (and subsequently).

Moving on to consider what is correct I think the most important consideration is that the model applied to generate output from the static trial should be the same as that applied to the dynamic model. 

I agree with Morgan that using the proximal axis means that we are treating the tibia differently to the femur. (I've known several quite competent biomechanists over the years who have failed to understand why anteversion isn't incorporated within the model and tibial torsion is). It can also "hide" issues associated with tibial torsion I've also been working clinically for the last five years with a Visual3D model which uses the distal axis and find that it is (saving unfinished)

**Comment by aaa34169** [comment]
thank you both. 

i resume your comments

_OK, thanks for the explanation Morgan, I'd forgotten this (I didn't know about this despite often thinking that static PiG knee outputs didn't look correct - I feel a little embarrassed to find out that the answer is so simple!)._

Vicon consider static PIG operation aims at calculating offsets. They are right but who decided to leave angles in model outputs without documented them ? 
Could we find a static posture highlighing abberant results from static pig operation ? 

_I think the logic you develop is correct and agree that CGM 1.0 should do what PiG does. I also agree that this is wrong and therefore should be corrected in CGM 1.1 (and subsequently)._

YES, i am agree.  However, currently i struggle to replicate static angles from PIG. CGM1 would be over if i do that.

_Moving on to consider what is correct I think the most important consideration is that the model applied to generate output from the static trial should be the same as that applied to the dynamic model._

A new feature of the CGM1.1

_I agree with Morgan that using the proximal axis means that we are treating the tibia differently to the femur. (I've known several quite competent biomechanists over the years who have failed to understand why anteversion isn't incorporated within the model and tibial torsion is). It can also "hide" issues associated with tibial torsion I've also been working clinically for the last five years with a Visual3D model which uses the distal axis and find that it is (saving unfinished)_

Is it a new feature of CGM1.1 or CGM2.i ?
Thus, it s no need Building a Proximal tibia. You just want to get a value of the Tibial Torsion. 
If we compute knee angles as rotation between femur and distal tibia, we likely return more knee varus valgus.

**Comment by rjbakersalford** [comment]
Sorry my train journey ended earlier so I didn't finish. ... I find the Visual3D convention of plotting knee angle with relation to the distal axis quite intuitive. Basically it means that the knee angles should have a mean value close to the tibial torsion. This forces you to think about tibial torsion whereas use of the proximal tibia effectively hides this issue from the user. 

The only effect on joint angles should be the expected offset in joint rotation. If there other two components are affected then we have got the wrong Cardan sequence (read my paper on joint angles in Journal of Biomechanics!). I don't think there should be any direct effect on kinematic fitting but there may be some indirect effects (the optimiser may approach the solution in a different manner and reach a different local minimum. Getting rid of the proximal tibia would also get rid of a lot of confusion.

Summarising i think that Morgan and I both agree that defining knee rotation in terms of the distal tibia is preferable for a number of reasons. The only reason I can see for maintaining what we have done is that it is the way that VICON have always presented data. If this was a graph that people look at regularly and pay a lot of attention to I would opt to keep with tradition. Given that this is a graph that most people ignore I think it would be preferable to change to a distal representation.

Richard

PS I've just thought of an advantage to the proximal system which is that if you want to import data into Opensim then most of the models effectively assume a proximal tibial axis system to describe the knee joint so you would have to subtract the offset when exporting data. Having said that most of the standard OpenSim models don't allow for any tibial torsion at all so probably shouldn't be used unless you've got a sufficient understanding of these issues to take care of the issues for yourself (in other words this doesn't change my overall opinion).

PPS I remember speaking to Roy Davis once and being surprised that he preferred a convention of using the distal tibial axis system. I guess it must have been the Helen Hayes crew that introduced this into the model.

**Comment by aaa34169** [comment]
I have battled a lot and i eventually succeed. 

My code now replicate outputs from vicon static pig operation. :-) It wasn t simple because i didn t want to break some concepts of my program. 

I can move on now. 

cheers

**Comment by Morgan435** [comment]
@rjbakersalford The consequences of the truncated information from PiG dynamic knee rotation graphs gets even better. I am not sure if you remember that, but it is the root of a mathematical discipline during reporting in Melbourne: gait curve arithmetic.
Which consist in working out tibial torsion by adding/subtracting the curves' value for a time instant, starting from pelvis then hip then (sometimes knee and ankle, but these are mostly 0) and comparing with foot progression, the difference being tibial torsion...
Everyone was very disappointed when I showed that we could replace gait curve arithmetic by just looking at the static knee rotation graphs to  work out 'PiG' tibial torsion :-)

**Comment by rjbakersalford** [comment]
Or just look at the value of the tibial torsion from the subject measurements!

**Comment by Morgan435** [comment]
too boring :-) And parameters are not available in polygon anymore.

**Comment by aaa34169** [comment]
I like your discussion. 
I can add tibial torsion value as an angle and you will get it from Polygon.
anyway

I try to go a bit further. 
for CGM1.1, if knee angles is relative to femur and distal tibia, you re agree that expression of knee joint moment  in distal segment is now in distal Tibia coordinate system.

**Comment by rjbakersalford** [comment]
So this is tricky. I don't think it makes any sense at all to express the knee moment in a coordinate system based upon the distal tibia. This will effectively project a component of true knee flexion moment onto the transverse plane. 

The most logical solution is to bring forward the implementation of outputting moments as the projections of onto the axes of the JCS which would be unaffected by whether a proximal or distal definition is used.

**Comment by rjbakersalford** [comment]
Another thought, One thing that we find quite useful is to plot the outputs from the static trial on the same graphs as we use to assess consistency. It can be clinically useful to see, for example, if pelvic tilt is different between walking and standing (and can also be useful as a quality assurance measure as well. 

With the conventions we are proposing this would effectively mean that tibial torsion (mathematically equivalent to knee rotation from the static trial) would be plotted on all the graphs to allow a very easy comparison with the walking data.

**Comment by aaa34169** [comment]
could you open a new issue richard please for your last request 

i have already done that :-) 
it s also possible to add clinical exam value ! 



Envoyé de mon iPhone

**Comment by rjbakersalford** [comment]
think you are both followers so you'll see that I've just published a blog post summarising this logic. I've done it mainly to get my own ideas straight but I think it does present a logical and consistent way of viewing the issues.

**Comment by aaa34169** [comment]
yes i see.  I like the advanced user paragraph :-)

I consider this issue closed now.  it was about static Vs dynamic PIG operation initially not tibial torsion.
