### ISSUE TITLE
Tibial torsion not calculated in 1.0 despite medial malleoli markers

### ISSUE THREAD

**Issue by Corey-Joseph** [pyCGM2/pyCGM2#40]
Hi there,

We have data using medial malleoli markers.  When we run the 1.0 version of CGM2 tibial torsion keeps resetting to zero, even after we manually enter the correct value. Our static trial does not have a KAD but has lateral and medial knee markers.

Is it possible to input the torsional values and run the 1.0 model or does there really need to be a KAD?

Thanks

**Comment by aaa34169** [comment]
hello Joseph

I ll check this point. 
tell me just how you use the library : 

 * do you use the Nexus embeded version of pycgm2 or the external version
 *  which version of Vicon Nexus

**Comment by Corey-Joseph** [comment]
Hi Fabian,

Thanks for getting back to me.  We are running cgm2 embedded in Nexus version 2.14.0 x64

Corey

**Comment by aaa34169** [comment]
OK, thanks. 
The good news is you use the last stable version of my package. 
I ll have a look and get back to you. 
Have you ever noticed the same issue with previous Nexus Version ? 
I got surprised you had this issue since i had not modified anything about the CGM1.0 in this pyCGM2 version

**Comment by Corey-Joseph** [comment]
Great! I've been examining data from pycgm2 through various versions of Nexus and had unexpected results in quite a few areas but I can't remember if this was present in other versions. I had heard that there were some bug fixes so made the change. 

I have only just discovered these results based on unexpected knee rotation data - I have 1.0 data that is completely different to PiG and I wonder if this is why. 

Tibial torsion seems to calculate fine with 1.1 and above.

**Comment by aaa34169** [comment]
Hi Corey

i checked with the nexus embeded pycgm2 package and my last version of pyCGM2. 
i did not manage to replicate your issue. 

I have a s static c3d with KAD and medial ankle. 
Each time i run the CGM1 calibration, the tibialTorsion is updated. 

could you share  your data ( only the static c3d and your mp ), please.

**Comment by Corey-Joseph** [comment]
Hi Fabian,

The static is with medial and lateral knee markers - not with KAD.  Perhaps this is why you cannot replicate the error?

Thanks,
Corey

**Comment by aaa34169** [comment]
Hi Corey

thanks for your feedback 

I found the error and fixed it. 
I will incorporate this fix in the next release of pyCGM2.
Soon, i will update my master branch with fix too. 
if you want to use it right now use my github beta branch.   

regards

Fabien

**Comment by Corey-Joseph** [comment]
Great! Thank you, Fabien.  We appreciate your work with this and CGM2 in general. It is fantastic to have this and we are moving towards using this clinically with adults.

**Comment by Corey-Joseph** [comment]
Hi again, Fabien.

I have a few questions i'd like to ask regarding my next steps from here. Are you able to email me at corey.joseph@monashhealth.org  ?  I don't know what your best contact is.

Thanks
