### ISSUE TITLE
missing mp.pyCGM2

### ISSUE THREAD

**Issue by kpchad** [pyCGM2/pyCGM2#7]
During Calibration, within getJsonFileContent > copyfile it references the mp.pyCGM2 file from SessionSettings. This file does not exist but looks like it was just removed on the last commit **f84fdfea308bb18f876bb7c27867d67176cf0123**

It seems to run smoothly if I recreate the file in my directory

**Comment by aaa34169** [comment]
Yes, that s true. I had a massive clean-up. I am going to fix that.  Sorry :-(

**Comment by kpchad** [comment]
No worries, I'm just trying to help out!

**Comment by aaa34169** [comment]
it s fixed. see pre-release version 3.0.8
[pre-release version 3.0.8]( https://github.com/pyCGM2/pyCGM2/releases/tag/version3.0.8)
