### ISSUE TITLE
osim error running cgm2.2 calibration

### ISSUE THREAD

**Issue by kpchad** [pyCGM2/pyCGM2#8]
CGM 1.0 through 2.1 ran smoothly on this dataset, but I get this error when I try trunning 2.2 calibration:

`11:47:13.886	Default	Run Python Operation	InverseKinematicsTool Failed: SimTK Exception thrown at AssemblyCondition_Markers.h:159: `

`11:47:13.886	Default	Run Python Operation	  Error detected by Simbody method Markers::addMarker(): Marker name 'LKNE' was already use for Marker 4. `

Any chance you are running into this error with the current version? if not, I can share a bit more details about the errors and osim model created so we can figure it out.

**Comment by aaa34169** [comment]
fix with with version 3.0.8
